# Generated by Django 5.2.15 on 2026-08-03 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0006_delete_subscriptionfee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('release_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('cover_art', models.ImageField(blank=True, null=True, upload_to='albums/covers/')),
                ('track_count', models.PositiveIntegerField(default=0)),
                ('listener_count', models.PositiveIntegerField(default=0)),
                ('stream_count', models.PositiveIntegerField(default=0)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='user.artist')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('release_type', models.CharField(choices=[('single', 'Single'), ('album', 'Album')], default='single', max_length=20)),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('release_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('co_artists', models.JSONField(blank=True, default=list)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('cover_art', models.ImageField(blank=True, null=True, upload_to='tracks/covers/')),
                ('audio_file', models.FileField(upload_to='tracks/audio/')),
                ('lyrics', models.TextField(blank=True, null=True)),
                ('listener_count', models.PositiveIntegerField(default=0)),
                ('stream_count', models.PositiveIntegerField(default=0)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='music.album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='user.artist')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
