# Generated by Django 5.2.15 on 2026-08-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_streamevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='feature_vector',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
