# Generated by Django 5.2.15 on 2026-08-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_track_feature_vector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='feature_vector',
        ),
        migrations.AddField(
            model_name='track',
            name='audio_features',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='track',
            name='behav_features',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='track',
            name='meta_features',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
